# -*- coding: utf-8 -*-
"""Revisar: +18 preguntas + 7 flashcards desde las 44 capturas del usuario
(data/imagenes_rutas/revisar/) — primera vez que esta pestana tiene volcado
propio (data/rutas/revisar.txt). Rellena los topics vacios comentarios,
revision-marcado y entrada-lapiz y refuerza seguimiento/comparar/proteger.
"""
import json

QF = "data/questions/revisar.json"
FF = "data/flashcards/revisar.json"
d = json.load(open(QF, encoding="utf-8"))

GRP = {"comentarios":"Comentarios","revision-marcado":"Revision — marcas y visualizacion",
       "seguimiento":"Seguimiento","comparar":"Comparar","proteger":"Proteger",
       "entrada-lapiz":"Entrada de lapiz","voz":"Voz","idioma":"Idioma",
       "accesibilidad":"Accesibilidad","revision-ortografica":"Revision"}

def mk(n, topic, tipo, enun, ops, resp, expl, cat="concepto"):
    return dict(sourceFile="revisar.json", bloque="Revisar — "+GRP[topic],
        section="revisar", topic=topic, subtopic=None, tema="Revisar",
        negativa=False, matching=None, generado=True, categoria=cat,
        id=f"revisar-{n}", sourceQuestionId=f"capt-rev-{n}", tipo=tipo,
        enunciado=enun, opciones=[{"letter":l,"text":t} for l,t in ops] if ops else [],
        respuesta=resp, explicacion=expl)

new = [
 mk(83,"comentarios","opcion_unica",
   "Dentro del globo de un comentario nuevo, ¿que combinacion lo publica?",
   [("A","Ctrl+Entrar"),("B","Solo Entrar"),("C","Mayus+Entrar"),("D","Ctrl+Mayus+Entrar")],
   "A",
   "El propio globo lo indica: «Sugerencia: Presione Ctrl + Entrar para publicar». El comentario se inserta con Alt+Ctrl+A o con «Nuevo comentario»."),
 mk(84,"comentarios","opcion_unica",
   "El desplegable «Eliminar» del grupo Comentarios ofrece cuatro opciones. ¿Cuales?",
   [("A","Eliminar; Eliminar todos los comentarios mostrados; Eliminar todos los comentarios del documento; Eliminar todos los comentarios resueltos"),
    ("B","Eliminar; Deshacer; Rehacer; Vaciar"),
    ("C","Eliminar comentario; Eliminar autor; Eliminar hilo; Eliminar seccion"),
    ("D","Solo «Eliminar» y «Eliminar todos»")],
   "A",
   "«...mostrados» depende del filtro activo; «...resueltos» solo borra los hilos marcados como resueltos."),
 mk(85,"comentarios","opcion_unica",
   "El boton «Mostrar comentarios» del grupo Comentarios permite verlos en dos disposiciones. ¿Cuales?",
   [("A","Contextual (en el margen, junto al texto) y Lista (panel lateral con todos)"),
    ("B","Globos y Notas al pie"),
    ("C","Vertical y Horizontal"),
    ("D","Resumido y Detallado")],
   "A",
   "«Contextual» ancla cada comentario al texto; «Lista» abre un panel con todos los hilos seguidos."),
 mk(86,"comentarios","verdadero_falso",
   "El atajo para insertar un comentario en Word 365 es Alt+Ctrl+A.",
   None, True,
   "Alt+Ctrl+A (InsertarComentario). No confundir con Alt+Ctrl+M, que en Word estandar es comentario pero aqui esta reasignado a la combinacion de correspondencia."),
 mk(87,"revision-marcado","opcion_unica",
   "El desplegable de «visualizacion del marcado» (junto a «Mostrar revisiones») ofrece cuatro modos. ¿Cuales?",
   [("A","Revisiones simples; Todas las revisiones; Sin revision; Original"),
    ("B","Borrador; Final; Original; Comparado"),
    ("C","Insertado; Eliminado; Movido; Formato"),
    ("D","Autor 1; Autor 2; Todos; Ninguno")],
   "A",
   "«Revisiones simples» muestra una linea roja en el margen; «Sin revision» oculta las marcas pero NO las quita; «Original» muestra el texto antes de los cambios."),
 mk(88,"revision-marcado","seleccion_multiple",
   "¿Cuales de estas opciones aparecen en el desplegable «Mostrar revisiones»?",
   [("A","Inserciones y eliminaciones"),("B","Formato"),("C","Globos"),
    ("D","Personas especificas"),("E","Ortografia")],
   ["A","B","C","D"],
   "«Globos» y «Personas especificas» tienen submenu. «Ortografia» no esta ahi."),
 mk(89,"revision-marcado","opcion_unica",
   "El submenu «Globos» de «Mostrar revisiones» tiene tres opciones. ¿Cuales?",
   [("A","Mostrar revisiones en globos; Mostrar todas las revisiones en linea; Mostrar solo formato en los globos"),
    ("B","Globos a la izquierda; Globos a la derecha; Sin globos"),
    ("C","Globos grandes; Globos pequenos; Globos automaticos"),
    ("D","Un globo por autor; Un globo por cambio; Un globo por pagina")],
   "A",
   "«...en linea» pega los cambios dentro del texto; «...solo formato en los globos» deja las inserciones/eliminaciones en linea y manda al margen solo los cambios de formato."),
 mk(90,"revision-marcado","opcion_unica",
   "En el desplegable «Filtrar todo el marcado», ¿que se puede hacer?",
   [("A","Restablecer todos los filtros y filtrar por criterios como «@me menciona»"),
    ("B","Cambiar el color de las marcas"),
    ("C","Bloquear el control de cambios"),
    ("D","Exportar las revisiones a un archivo")],
   "A",
   "Sirve para ver solo parte del marcado (por persona, por tipo, menciones...) sin perder el resto."),
 mk(91,"seguimiento","opcion_unica",
   "El desplegable «Aceptar» del grupo Seguimiento incluye, entre otras, ¿que opcion para terminar de golpe?",
   [("A","«Aceptar todos los cambios» y «Aceptar todos los cambios y detener seguimiento»"),
    ("B","«Aceptar y guardar»"),
    ("C","«Aceptar y cerrar»"),
    ("D","«Aceptar y comparar»")],
   "A",
   "Tambien tiene «Aceptar e ir al siguiente», «Aceptar este cambio» y «Aceptar todos los cambios mostrados» (segun el filtro). «Rechazar» tiene la lista simetrica."),
 mk(92,"seguimiento","opcion_unica",
   "¿Que hace «Bloquear seguimiento» (dentro del boton Control de cambios)?",
   [("A","Impide que otros autores desactiven el control de cambios; puede pedir una contrasena, pero «no es una caracteristica de seguridad»"),
    ("B","Bloquea el documento como solo lectura para todos"),
    ("C","Guarda una copia de seguridad de las revisiones"),
    ("D","Impide anadir mas comentarios")],
   "A",
   "El propio cuadro avisa de que la contrasena no cifra nada: solo evita que se apague el control de cambios sin conocerla."),
 mk(93,"seguimiento","verdadero_falso",
   "El atajo Ctrl+Mayus+E activa o desactiva el control de cambios.",
   None, True,
   "Ctrl+Mayus+E (HerramientActDesactMarcasCambio). El boton «Control de cambios» tambien ofrece «Para todos los usuarios» / «Solo los mios»."),
 mk(94,"comparar","opcion_unica",
   "El boton «Comparar» del grupo Comparar tiene dos comandos principales. ¿En que se diferencian «Comparar...» y «Combinar...»?",
   [("A","«Comparar» enfrenta DOS versiones de un documento (estilo juridico); «Combinar» fusiona las revisiones de VARIOS autores en un unico documento"),
    ("B","«Comparar» es para texto y «Combinar» para tablas"),
    ("C","«Comparar» crea un PDF y «Combinar» un DOCX"),
    ("D","Son sinonimos; cambia solo el nombre segun la version")],
   "A",
   "Hay un tercer comando, «Mostrar documentos de origen», para elegir que paneles se ven durante la comparacion."),
 mk(95,"comparar","seleccion_multiple",
   "En el cuadro «Comparar documentos», ademas de elegir el documento original y el revisado, ¿que se puede configurar?",
   [("A","«Mostrar cambios a:» nivel de caracter o nivel de palabra"),
    ("B","«Mostrar cambios en:» documento original, revisado o nuevo"),
    ("C","Que elementos comparar (movimientos, comentarios, formato, tablas, notas...)"),
    ("D","La etiqueta con la que se marcan los cambios"),
    ("E","El interlineado del documento resultante")],
   ["A","B","C","D"],
   "«Inserciones y eliminaciones» siempre se compara (casilla fija). Lo habitual es dejar «documento nuevo» para no tocar los originales."),
 mk(96,"proteger","opcion_unica",
   "En el panel «Restringir edicion», seccion 2 «Restricciones de edicion», ¿que valores ofrece el desplegable de tipo de edicion permitida?",
   [("A","Sin cambios (Solo lectura); Marcas de revision; Comentarios; Rellenar formularios"),
    ("B","Lectura; Escritura; Administrador"),
    ("C","Bajo; Medio; Alto"),
    ("D","Texto; Imagenes; Tablas; Todo")],
   "A",
   "«Marcas de revision» obliga a que todo cambio quede como control de cambios; «Comentarios» solo deja comentar; «Rellenar formularios» solo deja escribir en los controles de formulario."),
 mk(97,"proteger","verdadero_falso",
   "«Bloquear autores» evita que otros usuarios editen el texto que has seleccionado, pero solo funciona si el documento esta guardado en una ubicacion compartida admitida.",
   None, True,
   "Si el documento es local, el comando aparece deshabilitado («No se guardo el documento en una ubicacion compartida admitida»)."),
 mk(98,"entrada-lapiz","opcion_unica",
   "El desplegable «Ocultar entrada de lapiz» del grupo Entrada de lapiz ofrece dos opciones. ¿Cuales?",
   [("A","Ocultar entrada de lapiz; Eliminar todos los trazos en el documento"),
    ("B","Ocultar; Mostrar"),
    ("C","Lapiz; Resaltador; Borrador"),
    ("D","Convertir en texto; Convertir en forma")],
   "A",
   "«Ocultar» solo deja de mostrar los trazos manuscritos; «Eliminar todos los trazos» los borra de verdad."),
 mk(99,"revision-ortografica","opcion_unica",
   "¿Que hace la tecla Alt+F7 en Word 365?",
   [("A","Salta al siguiente error ortografico del documento"),
    ("B","Abre el Editor completo"),
    ("C","Cambia el idioma de correccion"),
    ("D","Cuenta las palabras")],
   "A",
   "F7 abre la revision completa (Editor); Alt+F7 va directamente marcando el siguiente error ortografico; Mayus+F7 abre Sinonimos.", "atajo"),
 mk(100,"revision-ortografica","opcion_unica",
   "El boton «Ortografia y gramatica» tiene una flecha con dos modos. ¿Cuales?",
   [("A","«Ortografia» (solo ortografia) y «Ortografia y gramatica» (ambas, marcada por defecto)"),
    ("B","«Rapida» y «Exhaustiva»"),
    ("C","«Espanol» e «Ingles»"),
    ("D","«Documento» y «Seleccion»")],
   "A",
   "Permite desactivar la comprobacion gramatical y revisar solo la ortografia."),
]

d.extend(new)
json.dump(d, open(QF, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
open(QF, "a", encoding="utf-8").write("\n")
print(f"preguntas: +{len(new)} (revisar-83..100)")

f = json.load(open(FF, encoding="utf-8"))
def fc(n, topic, front, back):
    return {"cardId": f"F-{n:03d}", "section":"revisar", "topic":topic, "subtopic":None,
            "cardType":"contenido", "priority":"alta", "front":front, "back":back,
            "sourceRefs":["data/rutas/revisar.txt (volcado del usuario)"],
            "knowledgeRefs":[], "questionRefs":[]}
fcs = [
 fc(70,"revision-marcado","Los 4 modos de visualizacion del marcado (desplegable junto a «Mostrar revisiones»).",
    "Revisiones simples (linea roja en el margen) · Todas las revisiones · Sin revision (oculta las marcas, NO las quita) · Original."),
 fc(71,"revision-marcado","Submenu «Globos» de «Mostrar revisiones»: las 3 opciones.",
    "Mostrar revisiones en globos · Mostrar todas las revisiones en linea · Mostrar solo formato en los globos."),
 fc(72,"seguimiento","«Aceptar» / «Rechazar» en el grupo Seguimiento: las 5 opciones de cada menu.",
    "Aceptar/Rechazar: e ir al siguiente · este cambio · todos los mostrados · todos · todos y detener seguimiento."),
 fc(73,"comparar","«Comparar...» vs «Combinar...» en la pestana Revisar.",
    "Comparar = enfrenta DOS versiones de un documento (estilo juridico). Combinar = fusiona las revisiones de VARIOS autores en un solo documento."),
 fc(74,"proteger","«Restringir edicion»: los 4 tipos de edicion que se pueden permitir.",
    "Sin cambios (Solo lectura) · Marcas de revision · Comentarios · Rellenar formularios. Se activa en «3. Comenzar a aplicar» (pide contrasena)."),
 fc(75,"comentarios","Atajos de comentarios y de control de cambios.",
    "Alt+Ctrl+A = insertar comentario · Ctrl+Entrar = publicar el comentario en el globo · Ctrl+Mayus+E = activar/desactivar el control de cambios."),
 fc(76,"comentarios","«Eliminar» (grupo Comentarios): las 4 opciones.",
    "Eliminar · Eliminar todos los comentarios mostrados · Eliminar todos los comentarios del documento · Eliminar todos los comentarios resueltos."),
]
f.extend(fcs)
json.dump(f, open(FF, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
open(FF, "a", encoding="utf-8").write("\n")
print(f"flashcards: +{len(fcs)} (F-070..F-076)")
