# -*- coding: utf-8 -*-
"""Minado del volcado data/rutas/inicio.txt (156 capturas del usuario de la
cinta Inicio, sep-2026) contra data/questions/inicio.json (457 preguntas,
el banco mas trabajado). Solo se generan preguntas sobre detalles de
cuadros de dialogo / desplegables SIN cobertura previa o con cobertura
muy baja, todos verificados en las capturas de data/imagenes_rutas/inicio/.
Nada de atajos nuevos (la fuente de atajos sigue siendo el volcado v2608);
la unica pregunta de atajo es la trampa Ctrl+= de Subindice, que la propia
captura del tooltip muestra y CLAUDE.md ya tiene resuelta.
"""
import json

F = "data/questions/inicio.json"
d = json.load(open(F, encoding="utf-8"))
n0 = max(int(q["id"].split("-")[-1]) for q in d)
tax = json.load(open("data/taxonomy.json", encoding="utf-8"))
NAME = {t["id"]: t["name"] for s in tax["sections"] if s["id"] == "inicio" for t in s["topics"]}
L = ["A", "B", "C", "D", "E", "F", "G", "H", "I"]

# (tipo, topic, categoria, negativa, enunciado, opciones|None, respuesta, explicacion, subtopic)
rows = [
 # ---------- PORTAPAPELES ----------
 ("verdadero_falso", "portapapeles", "concepto", False,
  "En el cuadro Pegado especial, la lista «Como:» ofrece formatos como «Mapa de bits» y «Mapa de bits independiente del dispositivo».",
  None, True,
  "La lista «Como:» del cuadro Pegado especial muestra los formatos disponibles según el contenido del Portapapeles (Mapa de bits, Mapa de bits independiente del dispositivo, Texto sin formato, HTML, Objeto…).", "Pegado especial"),
 ("opcion_unica", "portapapeles", "ruta", False,
  "En el cuadro Pegado especial, ¿qué opción inserta el contenido manteniendo un vínculo con el archivo de origen para que se actualice al cambiar este?",
  ["Pegar vínculo", "Pegar", "Mostrar como icono", "Mantener formato de origen"], "A",
  "El cuadro Pegado especial tiene dos botones de radio: «Pegar» (inserta una copia estática) y «Pegar vínculo» (inserta un vínculo que se actualiza con el origen).", "Pegado especial"),
 ("verdadero_falso", "portapapeles", "concepto", False,
  "El cuadro Pegado especial incluye una casilla «Mostrar como icono».",
  None, True,
  "Al marcarla, en vez del contenido se inserta un icono del objeto; se abre con doble clic.", "Pegado especial"),
 ("opcion_unica", "portapapeles", "ruta", False,
  "La opción «Establecer Pegar predeterminado…» del menú desplegable del botón Pegar, ¿qué abre?",
  ["Archivo ▸ Opciones ▸ Avanzadas, sección «Cortar, copiar y pegar»", "El cuadro Pegado especial", "El panel Portapapeles", "El cuadro Opciones de autocorrección"], "A",
  "Lleva directamente a la sección «Cortar, copiar y pegar» de Opciones avanzadas de Word, donde se fija el comportamiento por defecto al pegar dentro del mismo documento, entre documentos, desde otros programas, etc.", "Opciones de pegado"),
 ("verdadero_falso", "portapapeles", "ruta", False,
  "El menú desplegable del botón Pegar muestra los iconos de «Opciones de pegado» y, debajo, los enlaces «Pegado especial…» y «Establecer Pegar predeterminado…».",
  None, True,
  "Esa es exactamente la estructura del desplegable de Pegar en Word 365.", "Opciones de pegado"),

 # ---------- FUENTE ----------
 ("seleccion_multiple", "fuente", "ruta", False,
  "El desplegable «Efectos de texto y tipografía» (la A azul del grupo Fuente) tiene, además de la galería rápida de estilos, varios submenús. ¿Cuáles son submenús reales?",
  ["Contorno", "Sombra", "Reflejo", "Iluminado", "Conjuntos de estilos", "Bisel 3D", "Rotación"], ["A", "B", "C", "D", "E"],
  "Los submenús reales son Contorno, Sombra, Reflejo, Iluminado, Estilos de número, Ligaduras y Conjuntos de estilos. «Bisel 3D» y «Rotación» pertenecen al formato de forma/WordArt como objeto, no a este menú.", "Formato de carácter"),
 ("verdadero_falso", "fuente", "ruta", False,
  "El submenú «Efectos de texto y tipografía» incluye «Conjuntos de estilos», que aplica un conjunto estilístico (características OpenType) de la fuente al texto seleccionado.",
  None, True,
  "El submenú muestra un ejemplo «Predeterminado» y varias variantes «Individual» con la frase «El veloz murciélago hindú…».", "Formato de carácter"),
 ("verdadero_falso", "fuente", "ruta", False,
  "El submenú «Contorno» de Efectos de texto ofrece, además de la paleta de color, las opciones «Grosor» y «Guiones» para el trazo del contorno.",
  None, True,
  "«Grosor» abre una lista de anchos de línea (+ «Más líneas…») y «Guiones» una lista de patrones de trazo discontinuo (+ «Más líneas…»).", "Formato de carácter"),
 ("verdadero_falso", "fuente", "ruta", False,
  "El cuadro de diálogo Fuente tiene un botón «Efectos de texto:» en su parte inferior.",
  None, True,
  "Junto a «Establecer como predeterminado», el cuadro Fuente tiene el botón «Efectos de texto:», que abre el panel de efectos (relleno, contorno, sombra, reflejo, iluminado…).", "Formato de carácter"),
 ("seleccion_multiple", "fuente", "concepto", False,
  "En el bloque «Efectos» del cuadro de diálogo Fuente (Word 365), ¿qué casillas aparecen?",
  ["Tachado", "Doble tachado", "Superíndice", "Subíndice", "Versalitas", "Mayúsculas", "Oculto", "Contorno", "Relieve"], ["A", "B", "C", "D", "E", "F", "G"],
  "Las siete casillas son Tachado, Doble tachado, Superíndice, Subíndice, Versalitas, Mayúsculas y Oculto. «Contorno» y «Relieve» existían en versiones antiguas pero ya NO están en este cuadro (los efectos de contorno/sombra están ahora en el botón «Efectos de texto:»).", "Formato de carácter"),
 ("opcion_unica", "fuente", "concepto", False,
  "Además de la ficha «Fuente», ¿qué otra ficha tiene el cuadro de diálogo Fuente?",
  ["Avanzado", "Espaciado", "Efectos", "Escala"], "A",
  "La segunda ficha es «Avanzado»: ahí se ajusta la escala horizontal, el espaciado entre caracteres, la posición (subir/bajar), el interletraje y las características OpenType.", "Formato de carácter"),
 ("opcion_unica", "fuente", "ruta", True,
  "El desplegable «Cambiar mayúsculas y minúsculas» (Aa) del grupo Fuente ofrece varias opciones. Señale la que NO aparece:",
  ["Tipo oración.", "minúscula", "MAYÚSCULAS", "Solo iniciales de cada frase"], "D",
  "Las cinco opciones reales son: «Tipo oración.», «minúscula», «MAYÚSCULAS», «Poner En Mayúsculas Cada Palabra» y «Alternar mayúsculas y minúsculas». «Solo iniciales de cada frase» no existe.", "Mayúsculas y minúsculas"),
 ("relleno", "fuente", "ruta", False,
  "El desplegable «Cambiar mayúsculas y minúsculas» ofrece: «Tipo oración.», «minúscula», «MAYÚSCULAS», [1] y [2].",
  None, [["Poner En Mayúsculas Cada Palabra", "Poner en mayúsculas cada palabra"], ["Alternar mayúsculas y minúsculas"]],
  "Son las cinco opciones exactas del menú Aa del grupo Fuente.", "Mayúsculas y minúsculas"),
 ("opcion_unica", "fuente", "ruta", False,
  "En el menú Color de fuente ▸ «Degradado», la opción «Más degradados…» abre:",
  ["El panel «Formato de texto», con el relleno de texto en modo degradado", "El cuadro Fuente en la ficha Avanzado", "El cuadro Efectos de texto de la cinta Diseño", "El selector «Más colores»"], "A",
  "«Más degradados…» abre el panel lateral «Formato de texto» con «Relleno de texto: Relleno con degradado» y sus paradas de degradado, dirección y ángulo.", "Formato de carácter"),
 ("verdadero_falso", "fuente", "ruta", False,
  "El menú del botón «Color de resaltado del texto» incluye «Sin color» y «Detener resaltado».",
  None, True,
  "«Sin color» quita el resaltado de la selección; «Detener resaltado» desactiva el modo rotulador (el puntero deja de resaltar al arrastrar).", "Resaltar"),
 ("verdadero_falso", "fuente", "atajo", False,
  "La información en pantalla del botón Subíndice muestra «Ctrl+=», pero en esta instalación de Word esa combinación no aplica subíndice.",
  None, True,
  "⚠️ Ojo: el tooltip de la cinta muestra «Subíndice (Ctrl+=)» porque trae el esquema internacional, pero en esta instalación Ctrl+= no hace nada; el subíndice real se aplica con Ctrl+Mayús+- (prueba en vivo del usuario). Superíndice, en cambio, no muestra atajo en su tooltip y tampoco tiene ninguno aquí.", "Subíndice y superíndice"),
 ("verdadero_falso", "fuente", "ruta", False,
  "«Más subrayados…», al final del desplegable del botón Subrayado, abre el cuadro Fuente con el foco en el desplegable «Estilo de subrayado».",
  None, True,
  "Desde ahí se eligen estilos de línea que no están en el desplegable rápido (solo palabras, ondulado doble, etc.) y el «Color de subrayado».", "Formato de carácter"),
 ("opcion_unica", "fuente", "ruta", False,
  "¿Qué botón del cuadro de diálogo Fuente hace que la fuente elegida pase a ser la de todos los documentos nuevos basados en la plantilla actual?",
  ["Establecer como predeterminado", "Efectos de texto:", "Aceptar", "Avanzado"], "A",
  "«Establecer como predeterminado» pregunta si el cambio afecta solo a este documento o a todos los basados en la plantilla Normal.dotm.", "Formato de carácter"),

 # ---------- PARRAFO: espaciado / interlineado ----------
 ("seleccion_multiple", "parrafo-espaciado", "concepto", False,
  "En el cuadro Párrafo, el desplegable «Interlineado» ofrece:",
  ["Sencillo", "1,5 líneas", "Doble", "Mínimo", "Exacto", "Múltiple", "Ajustado"], ["A", "B", "C", "D", "E", "F"],
  "Los seis valores son Sencillo, 1,5 líneas, Doble, Mínimo, Exacto y Múltiple. «Ajustado» no existe.", None),
 ("opcion_unica", "parrafo-espaciado", "concepto", False,
  "¿Qué valor de Interlineado fija una altura de línea en puntos que NO crece aunque la fuente sea más grande (y puede recortar el texto)?",
  ["Exacto", "Mínimo", "Múltiple", "Doble"], "A",
  "«Exacto» impone una altura fija. «Mínimo» también se indica en puntos pero se agranda si el contenido de la línea lo necesita.", None),
 ("opcion_unica", "parrafo-espaciado", "ruta", False,
  "El botón desplegable «Espaciado entre líneas y párrafos» de la cinta ofrece, además de los valores 1,0 a 3,0 y «Opciones de interlineado…»:",
  ["«Agregar espacio antes del párrafo» y «Quitar espacio después del párrafo»", "«Sangría francesa» y «Primera línea»", "«Bordes y sombreado…»", "«Definir nuevo interlineado…»"], "A",
  "Según el estado del párrafo, la última línea del menú alterna entre agregar/quitar el espacio anterior y posterior del párrafo.", None),
 ("verdadero_falso", "parrafo-espaciado", "ruta", False,
  "«Opciones de interlineado…», dentro del desplegable de interlineado de la cinta, abre el cuadro Párrafo en la ficha «Sangría y espacio».",
  None, True,
  "Es la misma ficha que abre el iniciador del grupo Párrafo.", None),
 ("relleno", "parrafo-espaciado", "ruta", False,
  "El desplegable de interlineado de la cinta ofrece los valores [1], 1,15, [2], 2,0, 2,5 y [3].",
  None, [["1,0", "1.0"], ["1,5", "1.5"], ["3,0", "3.0"]],
  "Son los seis valores rápidos del botón «Espaciado entre líneas y párrafos».", None),
 ("opcion_unica", "parrafo-espaciado", "concepto", False,
  "En el cuadro Párrafo, la casilla «No agregar espacio entre párrafos del mismo estilo» pertenece al bloque:",
  ["Espaciado", "Sangría", "General", "Líneas y saltos de página"], "A",
  "Está junto a los campos Anterior / Posterior / Interlineado del bloque «Espaciado».", None),

 # ---------- PARRAFO: sangria ----------
 ("opcion_unica", "parrafo-sangria", "concepto", True,
  "El campo «Especial» del bloque Sangría del cuadro Párrafo tiene tres valores. Señale el que NO es uno de ellos:",
  ["(ninguna)", "Primera línea", "Sangría francesa", "Sangría simétrica"], "D",
  "Los tres valores de «Especial» son «(ninguna)», «Primera línea» y «Sangría francesa». «Sangrías simétricas» existe, pero es una casilla independiente, no un valor de este desplegable.", None),
 ("verdadero_falso", "parrafo-sangria", "concepto", False,
  "Al marcar «Sangrías simétricas» en el cuadro Párrafo, las etiquetas «Izquierda» y «Derecha» pasan a ser «Interior» y «Exterior».",
  None, True,
  "Es para documentos que se imprimen a doble cara: la sangría «interior» queda del lado de la encuadernación.", None),

 # ---------- PARRAFO: nivel de esquema / fichas ----------
 ("verdadero_falso", "parrafo-alineacion", "concepto", False,
  "El campo «Nivel de esquema» del cuadro Párrafo admite «Texto independiente» y de «Nivel 1» a «Nivel 9».",
  None, True,
  "Asignar un nivel 1-9 a un párrafo lo hace aparecer en el panel de Navegación y en la Tabla de contenido aunque no tenga estilo de título.", None),
 ("verdadero_falso", "parrafo-alineacion", "concepto", False,
  "La casilla «Contraído de forma predeterminada» del cuadro Párrafo solo se habilita si el «Nivel de esquema» es de Nivel 1 a Nivel 9.",
  None, True,
  "Con «Texto independiente» esa casilla está atenuada: solo tiene sentido contraer/expandir encabezados con nivel de esquema.", None),
 ("opcion_unica", "parrafo-alineacion", "concepto", False,
  "¿Cuáles son las dos fichas del cuadro de diálogo Párrafo?",
  ["«Sangría y espacio» y «Líneas y saltos de página»", "«Sangría» y «Espaciado»", "«Párrafo» y «Avanzado»", "«General» y «Tabulaciones»"], "A",
  "La primera reúne alineación, sangría y espaciado; la segunda, el control de líneas viudas/huérfanas, «Conservar con el siguiente», saltos, etc.", None),
 ("opcion_unica", "parrafo-tabulaciones", "ruta", False,
  "¿Qué botón hay en la esquina inferior izquierda del cuadro de diálogo Párrafo?",
  ["Tabulaciones…", "Bordes…", "Sangría…", "Fuente…"], "A",
  "El botón «Tabulaciones…» abre el cuadro donde se definen las paradas de tabulación (posición, alineación, relleno).", None),
 ("opcion_unica", "parrafo-alineacion", "concepto", False,
  "En el cuadro Párrafo, el desplegable «Alineación» del bloque General ofrece:",
  ["Izquierda, Centrada, Derecha, Justificada", "Izquierda, Centrada, Derecha, Distribuida, Justificada", "Superior, Centrada, Inferior", "Izquierda y Derecha únicamente"], "A",
  "Son las cuatro alineaciones horizontales de párrafo; se corresponden con Ctrl+Q, Ctrl+T, Ctrl+D y Ctrl+J en esta instalación.", None),

 # ---------- PARRAFO: bordes y sombreado ----------
 ("opcion_unica", "parrafo-bordes", "ruta", True,
  "En el desplegable del botón «Bordes» del grupo Párrafo, ¿cuál de estas opciones NO aparece?",
  ["Línea horizontal", "Dibujar tabla", "Ver cuadrículas", "Autoajustar bordes"], "D",
  "El desplegable de Bordes termina con «Línea horizontal», «Dibujar tabla», «Ver cuadrículas» y «Bordes y sombreado…». «Autoajustar bordes» no existe.", None),
 ("verdadero_falso", "parrafo-bordes", "ruta", False,
  "El desplegable del botón «Bordes» (grupo Párrafo) incluye «Dibujar tabla» y «Ver cuadrículas».",
  None, True,
  "Además de los bordes de párrafo, ese menú da acceso rápido a dibujar una tabla y a mostrar las líneas de cuadrícula no imprimibles.", None),
 ("opcion_unica", "parrafo-bordes", "ruta", False,
  "El cuadro «Bordes y sombreado» tiene tres fichas: «Bordes», «Sombreado» y…",
  ["Borde de página", "Marca de agua", "Tramas", "Bordes internos"], "A",
  "La ficha «Borde de página» aplica un marco a toda la página y añade el campo «Arte» con bordes decorativos.", None),
 ("opcion_unica", "parrafo-bordes", "concepto", False,
  "El campo «Arte» (marcos decorativos con dibujos: árboles, corazones, lápices…) del cuadro «Bordes y sombreado» aparece solo en la ficha:",
  ["Borde de página", "Bordes", "Sombreado", "Opciones"], "A",
  "«Arte» solo tiene sentido para el borde de toda la página; no existe para el borde de un párrafo.", None),
 ("seleccion_multiple", "parrafo-bordes", "concepto", False,
  "En la ficha «Bordes» del cuadro «Bordes y sombreado», el panel «Valor» ofrece:",
  ["Ninguno", "Cuadro", "Sombra", "3D", "Personalizado", "Doble", "Relieve"], ["A", "B", "C", "D", "E"],
  "Los cinco presets de «Valor» son Ninguno, Cuadro, Sombra, 3D y Personalizado. «Doble» es un estilo de línea, no un valor; «Relieve» no existe aquí.", None),
 ("opcion_unica", "parrafo-bordes", "concepto", False,
  "En la ficha «Bordes» de «Bordes y sombreado», el desplegable «Aplicar a» permite elegir entre:",
  ["Párrafo y Texto", "Página y Sección", "Documento y Plantilla", "Tabla y Celda"], "A",
  "El borde puede rodear todo el párrafo o solo el texto seleccionado dentro de él.", None),
 ("verdadero_falso", "parrafo-bordes", "concepto", False,
  "En la ficha «Borde de página» de «Bordes y sombreado», el desplegable «Aplicar a» incluye la opción «Esta sección: solo la primera página».",
  None, True,
  "También «Todo el documento», «Esta sección» y «Esta sección: todas menos la primera página».", None),
 ("opcion_unica", "parrafo-bordes", "concepto", False,
  "Además del bloque «Relleno», ¿qué otro bloque tiene la ficha «Sombreado» del cuadro «Bordes y sombreado»?",
  ["Tramas (Estilo y Color)", "Arte", "Valor", "Ancho"], "A",
  "«Tramas» aplica un patrón (Claro, 5%, 10%, rayas, cuadrículas…) con su propio color sobre el relleno.", None),
 ("verdadero_falso", "parrafo-bordes", "concepto", False,
  "El botón «Opciones…» de la ficha «Bordes» de «Bordes y sombreado» fija la distancia (margen) entre el borde y el texto.",
  None, True,
  "Permite ajustar por separado el margen superior, inferior, izquierdo y derecho entre la línea del borde y el contenido del párrafo.", None),

 # ---------- PARRAFO: listas, viñetas, numeracion ----------
 ("seleccion_multiple", "parrafo-listas", "ruta", False,
  "En la «Biblioteca de numeración» (desplegable del botón Numeración), ¿qué formatos aparecen?",
  ["1. 2. 3.", "1) 2) 3)", "I. II. III.", "A. B. C.", "a) b) c)", "Primero, Segundo, Tercero", "① ② ③"], ["A", "B", "C", "D", "E"],
  "La biblioteca ofrece «Ninguna», 1.2.3. / 1)2)3) / I.II.III. / A.B.C. / a)b)c) / a.b.c. / i.ii.iii. Los formatos de texto («Primero…») o círculos numerados no están en la biblioteca (se harían con «Definir nuevo formato de número…»).", None),
 ("opcion_unica", "parrafo-listas", "ruta", False,
  "En el cuadro «Definir nuevo formato de número», ¿qué botón permite cambiar la fuente, el tamaño y el color del número?",
  ["Fuente…", "Símbolo…", "Imagen…", "Formato…"], "A",
  "El botón «Fuente…» abre el cuadro Fuente aplicado solo al carácter del número (no al texto del elemento de lista).", None),
 ("verdadero_falso", "parrafo-listas", "ruta", False,
  "El cuadro «Definir nuevo formato de número» tiene un desplegable «Estilo de número» (1,2,3 / I,II,III / a,b,c / 1º,2º,3º / (ninguno)…) y un campo «Alineación» (Izquierda, Centrada, Derecha).",
  None, True,
  "«Formato de número» permite además añadir texto fijo alrededor del número, p. ej. «Art. 1.-».", None),
 ("opcion_unica", "parrafo-listas", "ruta", False,
  "El cuadro «Definir nueva viñeta» ofrece tres orígenes para la viñeta:",
  ["Símbolo, Imagen y Fuente", "Símbolo, Ecuación y Color", "Imagen, Icono y Forma", "Texto, Número y Símbolo"], "A",
  "«Símbolo…» elige un carácter de una fuente; «Imagen…» usa un archivo o imagen en línea; «Fuente…» fija el formato de carácter de la viñeta. Además hay un campo «Alineación».", None),
 ("verdadero_falso", "parrafo-listas", "ruta", False,
  "El cuadro «Definir nueva lista con varios niveles» permite configurar de forma independiente cada uno de los 9 niveles de la lista.",
  None, True,
  "Se elige el nivel en la lista «Haga clic en el nivel que desea modificar» (1 a 9) y se define su formato de número, estilo, posición y sangría.", None),
 ("opcion_unica", "parrafo-listas", "ruta", False,
  "En «Definir nueva lista con varios niveles», el botón «Establecer para todos los niveles…» sirve para:",
  ["Aplicar de una vez la posición y la sangría a los nueve niveles", "Convertir la lista en una lista de un solo nivel", "Guardar la lista como estilo", "Reiniciar la numeración de todos los niveles"], "A",
  "Fija la posición del primer nivel y el incremento de sangría adicional por nivel, y lo propaga a todos.", None),
 ("opcion_unica", "parrafo-listas", "ruta", False,
  "El desplegable «Lista multinivel» ofrece, además de «Definir nueva lista multinivel…»:",
  ["Definir nuevo estilo de lista…", "Definir nueva viñeta…", "Definir nuevo formato de número…", "Establecer valor de numeración…"], "A",
  "«Definir nuevo estilo de lista…» crea un estilo de lista reutilizable (aparece luego en la galería de estilos de lista); «Definir nueva lista multinivel…» define solo el formato para la lista actual.", None),
 ("verdadero_falso", "parrafo-listas", "ruta", False,
  "El desplegable «Lista multinivel» muestra una sección «Lista actual» con el formato multinivel aplicado en ese momento, encima de la «Biblioteca de listas».",
  None, True,
  "Debajo aparece la «Biblioteca de listas» con «Ninguna» y los presets (incluidos los que enlazan cada nivel con Título 1, Título 2, Título 3).", None),

 # ---------- ESTILOS ----------
 ("seleccion_multiple", "estilos", "concepto", False,
  "¿Cuáles son estilos reales de la galería de Estilos de la pestaña Inicio?",
  ["Cita destacada", "Referencia intensa", "Título del libro", "Énfasis intenso", "Encabezado 1", "Nota al margen", "Resaltado fuerte"], ["A", "B", "C", "D"],
  "La galería incluye Normal, Sin espaciado, Título 1, Título 2, Título, Subtítulo, Énfasis sutil, Énfasis, Énfasis intenso, Fuerte, Cita, Cita destacada, Referencia sutil, Referencia intensa, Título del libro y Párrafo de lista. «Encabezado 1» se llama aquí «Título 1»; «Nota al margen» y «Resaltado fuerte» no existen.", None),
 ("opcion_unica", "estilos", "ruta", False,
  "El menú que aparece bajo la galería de Estilos (flecha «Más») ofrece «Crear un estilo», «Borrar formato» y:",
  ["Aplicar estilos…", "Administrar estilos…", "Inspector de estilo", "Nuevo estilo rápido"], "A",
  "«Aplicar estilos…» abre un cuadro flotante pequeño para escribir el nombre del estilo y aplicarlo (equivale a Ctrl+Mayús+W).", None),
 ("opcion_unica", "estilos", "ruta", False,
  "Al crear un estilo nuevo y pulsar «Modificar…», el campo «Tipo de estilo» aparece por defecto como:",
  ["Vinculado (párrafo y carácter)", "Párrafo", "Carácter", "Lista"], "A",
  "«Vinculado (párrafo y carácter)» aplica formato de párrafo si no hay selección y solo formato de carácter si hay texto seleccionado dentro del párrafo.", None),
 ("seleccion_multiple", "estilos", "concepto", False,
  "El campo «Tipo de estilo» del cuadro de creación/modificación de estilo ofrece:",
  ["Párrafo", "Carácter", "Vinculado (párrafo y carácter)", "Tabla", "Lista", "Sección", "Página"], ["A", "B", "C", "D", "E"],
  "Los cinco tipos son Párrafo, Carácter, Vinculado (párrafo y carácter), Tabla y Lista. No hay tipos «Sección» ni «Página».", None),
 ("seleccion_multiple", "estilos", "ruta", False,
  "El menú «Formato ▾» del cuadro Modificar/Crear estilo da acceso a cuadros de:",
  ["Fuente", "Párrafo", "Tabulaciones", "Borde", "Numeración", "Método abreviado", "Efectos de texto", "Columnas"], ["A", "B", "C", "D", "E", "F", "G"],
  "El menú «Formato ▾» tiene: Fuente, Párrafo, Tabulaciones, Borde, Idioma, Marco, Numeración, Método abreviado y Efectos de texto. «Columnas» no está (no es formato de estilo de párrafo).", None),
 ("opcion_unica", "estilos", "concepto", False,
  "En el cuadro Modificar estilo, ¿qué casilla hace que, al cambiar a mano el formato de cualquier párrafo con ese estilo, se redefina automáticamente el estilo entero?",
  ["Actualizar automáticamente", "Agregar a la galería de estilos", "Solo en este documento", "Vinculado"], "A",
  "«Actualizar automáticamente» es cómodo pero peligroso: un retoque local reformatea todos los párrafos del documento con ese estilo.", None),
 ("opcion_unica", "estilos", "concepto", False,
  "Las dos opciones de alcance al pie del cuadro de creación de estilo son «Solo en este documento» y:",
  ["Documentos nuevos basados en esta plantilla", "Todos los documentos abiertos", "Esta sección", "La plantilla y los documentos existentes"], "A",
  "La segunda guarda el estilo en la plantilla (p. ej. Normal.dotm), de modo que los documentos nuevos lo tendrán.", None),
 ("verdadero_falso", "estilos", "concepto", False,
  "El campo «Estilo del párrafo siguiente» define qué estilo se aplica al párrafo que se crea al pulsar Enter tras un párrafo con este estilo.",
  None, True,
  "Por eso «Título 1» suele tener como párrafo siguiente «Normal»: tras el título se sigue escribiendo texto normal.", None),
 ("opcion_unica", "estilos", "ruta", False,
  "El panel Estilos (iniciador del grupo) tiene tres botones en su parte inferior: «Nuevo estilo», «Inspector de estilo» y:",
  ["Administrar estilos", "Borrar todo", "Opciones", "Aplicar estilos"], "A",
  "«Administrar estilos» abre el cuadro completo (Modificar / Recomendar / Restringir / Establecer valores predeterminados).", None),
 ("verdadero_falso", "estilos", "ruta", False,
  "El panel Estilos ofrece las casillas «Mostrar vista previa» y «Deshabilitar estilos vinculados».",
  None, True,
  "«Mostrar vista previa» pinta cada nombre con su formato; «Deshabilitar estilos vinculados» fuerza a que los estilos vinculados actúen siempre como estilo de párrafo.", None),
 ("opcion_unica", "estilos", "ruta", True,
  "En el cuadro «Opciones del panel Estilos», el desplegable «Seleccionar cómo se ordena la lista» NO ofrece:",
  ["Por color", "Alfabético", "Por recomendación", "Fuente"], "A",
  "Ofrece «Como en la recomendación», «Alfabético», «Fuente», «Basado en» y «Por tipo». No hay orden «Por color».", None),
 ("verdadero_falso", "estilos", "ruta", False,
  "El cuadro «Opciones del panel Estilos» permite elegir qué estilos mostrar (Recomendado / En uso / En el documento actual / Todos los estilos).",
  None, True,
  "También decide si se muestran como estilos independientes el formato de párrafo, de fuente y de numeración/viñetas aplicados manualmente.", None),
 ("opcion_unica", "estilos", "concepto", False,
  "El «Inspector de estilo» (botón del panel Estilos) muestra:",
  ["Por separado el formato de párrafo y el formato de texto (carácter) de la selección, con botones para restablecer cada uno", "La lista de todos los estilos del documento ordenada por uso", "Un historial de los cambios de formato del documento", "Las diferencias entre dos estilos"], "A",
  "Ayuda a distinguir qué parte del aspecto viene del estilo y qué parte es formato directo (manual), y a quitar solo una de las dos capas.", None),

 # ---------- EDICION ----------
 ("opcion_unica", "edicion", "ruta", False,
  "La flecha del botón «Buscar» del grupo Edición despliega tres opciones: «Buscar», «Búsqueda avanzada…» e:",
  ["Ir a…", "Reemplazar…", "Resaltado de lectura", "Buscar en"], "A",
  "«Buscar» abre el panel Navegación; «Búsqueda avanzada…» e «Ir a…» abren el cuadro clásico «Buscar y reemplazar» en la ficha correspondiente.", "Buscar y reemplazar"),
 ("opcion_unica", "edicion", "ruta", False,
  "En la ficha «Buscar» del cuadro «Buscar y reemplazar», ¿para qué sirve el botón «Resaltado de lectura ▾»?",
  ["Resaltar en pantalla todas las coincidencias a la vez (y poder quitarlas)", "Imprimir solo los párrafos con coincidencias", "Marcar las coincidencias con un comentario", "Aplicar color de resaltado permanente al texto encontrado"], "A",
  "El resaltado de lectura es temporal (en pantalla); «Borrar resaltado» lo quita. No modifica el formato guardado del documento.", "Buscar y reemplazar"),
 ("verdadero_falso", "edicion", "ruta", False,
  "El cuadro «Buscar y reemplazar» tiene un botón «Buscar en ▾» que limita la búsqueda a una parte del documento (p. ej. el documento principal, o los encabezados y pies).",
  None, True,
  "Suele usarse tras seleccionar un fragmento: «Buscar en ▸ Selección actual».", "Buscar y reemplazar"),
 ("seleccion_multiple", "edicion", "concepto", False,
  "Al pulsar «Más >>» en el cuadro «Buscar y reemplazar» se muestran opciones de búsqueda. ¿Cuáles son reales?",
  ["Coincidir mayúsculas y minúsculas", "Solo palabras completas", "Usar caracteres comodín", "Todas las formas de la palabra (inglés)", "Buscar sinónimos automáticamente", "Resaltar resultados en negrita"], ["A", "B", "C", "D"],
  "También están «Suena como (inglés)», «Omitir signos de puntuación» y los botones «Formato», «Especial» y «Sin formato». «Buscar sinónimos» y «Resaltar en negrita» no existen ahí.", "Buscar y reemplazar"),
 ("opcion_unica", "edicion", "ruta", False,
  "¿Cuántas fichas tiene el cuadro de diálogo «Buscar y reemplazar»?",
  ["Tres: Buscar, Reemplazar e Ir a", "Dos: Buscar y Reemplazar", "Cuatro: Buscar, Reemplazar, Ir a y Opciones", "Una sola"], "A",
  "«Ir a» comparte cuadro con Buscar y Reemplazar; se llega a ella con Ctrl+I (Ir a) en esta instalación o desde la flecha del botón Buscar.", "Ir a"),
 ("seleccion_multiple", "edicion", "concepto", False,
  "En la ficha «Ir a» del cuadro «Buscar y reemplazar», ¿qué destinos de la lista «Ir a:» son reales?",
  ["Página", "Sección", "Línea", "Marcador", "Nota al pie", "Estilo", "Palabra"], ["A", "B", "C", "D", "E"],
  "La lista incluye Página, Sección, Línea, Marcador, Comentario, Nota al pie, Nota al final, Campo, Tabla, Gráfico, Ecuación, Objeto y Título. No se puede «Ir a» un estilo o una palabra concreta desde aquí.", "Ir a"),
 ("verdadero_falso", "edicion", "concepto", False,
  "En la ficha «Ir a», si en el número se escribe «+4» el cursor avanza 4 elementos (páginas, líneas…) desde la posición actual.",
  None, True,
  "El propio cuadro lo explica: «escribiendo +4 se desplazará cuatro elementos hacia adelante»; «-2» retrocedería dos.", "Ir a"),
 ("opcion_unica", "edicion", "ruta", False,
  "El desplegable «Seleccionar» del grupo Edición ofrece «Seleccionar todo», «Seleccionar objetos», «Seleccionar texto con formato similar» y:",
  ["Panel de selección…", "Seleccionar sección", "Modo extendido", "Seleccionar hasta el final"], "A",
  "«Panel de selección…» abre el panel que lista los objetos de la página y permite mostrarlos, ocultarlos o reordenarlos.", "Seleccionar"),
 ("opcion_unica", "edicion", "concepto", False,
  "«Seleccionar texto con formato similar» (menú Seleccionar) sirve para:",
  ["Seleccionar de una vez todo el texto del documento que tiene el mismo formato que el texto actual", "Buscar texto parecido en significado", "Aplicar el formato del texto actual al resto del documento", "Seleccionar el párrafo actual y el siguiente"], "A",
  "Útil para cambiar a la vez, por ejemplo, todos los fragmentos que quedaron en un tamaño o color concreto.", "Seleccionar"),
 ("verdadero_falso", "edicion", "ruta", False,
  "«Panel de selección…» abre un panel que enumera todos los objetos de la página y permite ocultarlos o cambiar su orden de apilamiento.",
  None, True,
  "Su información en pantalla lo describe como «Consulte una lista de todos los objetos… más fácil seleccionarlos, cambiarlos de orden o cambiar su visibilidad».", "Seleccionar"),

 # ---------- VOZ / COMPLEMENTOS ----------
 ("verdadero_falso", "voz", "ruta", False,
  "El botón «Dictar» del grupo Voz tiene una flecha desplegable para elegir el idioma de dictado y ajustar sus opciones.",
  None, True,
  "El dictado por voz necesita conexión a internet; el idioma se elige en ese desplegable.", "Dictado"),
 ("verdadero_falso", "complementos", "ruta", False,
  "El botón «Complementos» del grupo Complementos abre la galería/tienda de complementos de Office, con la sección «Mis complementos».",
  None, True,
  "Desde ahí se instalan complementos (Wikipedia, diccionarios, etc.) que luego aparecen en la cinta o en un panel.", None),

 # ---------- EMPAREJAMIENTO ----------
 ("emparejamiento", "fuente", "ruta", False,
  "Relaciona cada opción «Más…» de un desplegable del grupo Fuente/Párrafo con el cuadro o panel que abre:",
  None, None,
  "Cada «Más…» lleva a un cuadro distinto; ninguno abre el cuadro Tabulaciones (ese está en el desplegable de interlineado y en el cuadro Párrafo).", None),
 ("emparejamiento", "parrafo-bordes", "concepto", False,
  "Relaciona cada ficha del cuadro «Bordes y sombreado» con lo que contiene:",
  None, None,
  "«Arte» solo está en «Borde de página»; las tramas solo en «Sombreado».", None),
]

emp_data = {
 "Relaciona cada opción «Más…» de un desplegable del grupo Fuente/Párrafo con el cuadro o panel que abre:": {
   "left": [
     {"id": "1", "label": "Subrayado ▸ Más subrayados…"},
     {"id": "2", "label": "Espaciado ▸ Opciones de interlineado…"},
     {"id": "3", "label": "Bordes ▸ Bordes y sombreado…"},
     {"id": "4", "label": "Color de fuente ▸ Degradado ▸ Más degradados…"},
   ],
   "right": [
     {"id": "A", "label": "Cuadro Fuente, foco en «Estilo de subrayado»"},
     {"id": "B", "label": "Cuadro Párrafo, ficha «Sangría y espacio»"},
     {"id": "C", "label": "Cuadro «Bordes y sombreado»"},
     {"id": "D", "label": "Panel «Formato de texto» (relleno con degradado)"},
     {"id": "E", "label": "Cuadro «Tabulaciones»"},
   ],
   "correct": {"1": "A", "2": "B", "3": "C", "4": "D"},
 },
 "Relaciona cada ficha del cuadro «Bordes y sombreado» con lo que contiene:": {
   "left": [
     {"id": "1", "label": "Bordes"},
     {"id": "2", "label": "Borde de página"},
     {"id": "3", "label": "Sombreado"},
   ],
   "right": [
     {"id": "A", "label": "Valor/Estilo/Color/Ancho + «Aplicar a: Párrafo o Texto»"},
     {"id": "B", "label": "Igual que Bordes + campo «Arte» + «Aplicar a: Todo el documento/Sección»"},
     {"id": "C", "label": "«Relleno» + «Tramas» (Estilo y Color)"},
     {"id": "D", "label": "«Origen del papel» para la primera página"},
   ],
   "correct": {"1": "A", "2": "B", "3": "C"},
 },
}

out = []
for k, r in enumerate(rows, 1):
    tipo, topic, cat, neg, enun, opts, resp, expl, sub = r
    q = {
        "id": f"inicio-{n0+k}", "sourceFile": "inicio.json",
        "bloque": f"Inicio — {NAME[topic]}", "tipo": tipo, "categoria": cat,
        "negativa": neg, "section": "inicio", "topic": topic, "subtopic": sub,
        "tema": NAME[topic], "sourceQuestionId": f"rutas-inicio-{k:02d}", "generado": True,
        "enunciado": enun, "opciones": [], "matching": None, "respuesta": resp,
        "explicacion": expl,
    }
    if tipo in ("opcion_unica", "seleccion_multiple"):
        q["opciones"] = [{"letter": L[i], "text": t} for i, t in enumerate(opts)]
    if tipo == "emparejamiento":
        m = emp_data[enun]
        q["matching"] = m
        q["respuesta"] = dict(m["correct"])
    out.append(q)

d.extend(out)
json.dump(d, open(F, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
open(F, "a", encoding="utf-8").write("\n")
print("añadidas", len(out), "-> total", len(d))
