# -*- coding: utf-8 -*-
# Eje 6: sube la densidad de negativa en inicio/insertar (2.7% -> ~6%),
# igualando al resto del banco. Mismo patron que scripts/gen_negativas.py:
# opcion_unica, "senale la INCORRECTA", 3 opciones verdaderas + 1 falsa
# (la falsa es la respuesta correcta). Solo hechos ya establecidos en
# CLAUDE.md/esta sesion o conocimiento estandar y seguro de Word.
import json

tax = json.load(open("data/taxonomy.json", encoding="utf-8"))
NAME = {s["id"]: {t["id"]: t["name"] for t in s["topics"]} for s in tax["sections"]}
TO = {s["id"]: {t["id"]: i for i, t in enumerate(s["topics"])} for s in tax["sections"]}

# (section, topic, [4 opciones], letra_correcta=la FALSA, explicacion)
Q = [
# ---------- INICIO (+14) ----------
("inicio","fuente",
 ["Ctrl+M abre el cuadro Fuente con el foco en el campo Fuente (nombre).",
  "Ctrl+Mayús+M abre el mismo cuadro con el foco en Tamaño.",
  "Superíndice tiene un atajo de teclado directo, Ctrl+Mayús++.",
  "Ctrl+Barra espaciadora quita el formato de carácter aplicado manualmente."],
 "C","Superíndice NO tiene atajo en esta instalación (prueba en vivo): solo desde la casilla del cuadro Fuente o el botón de la cinta."),
("inicio","fuente",
 ["El color de subrayado se puede fijar de forma independiente al color de fuente.",
  "Ctrl+Mayús+S aplica subrayado.",
  "El subrayado solo admite el estilo de línea simple; no hay otros estilos disponibles.",
  "El tamaño de fuente se puede agrandar de punto en punto con Ctrl+Alt+>."],
 "C","El cuadro Fuente ofrece varios estilos de subrayado (doble, punteado, ondulado, grueso…), no solo el simple."),
("inicio","fuente",
 ["Subíndice se activa con Ctrl+Mayús+- (la tecla del guión).",
  "Superíndice no tiene atajo de teclado en esta instalación.",
  "Ctrl+= activa el subíndice en esta instalación.",
  "Superíndice se activa desde la casilla del cuadro Fuente o el botón de la cinta."],
 "C","Ctrl+= es el esquema internacional; en esta instalación no hace nada (prueba en vivo). El subíndice real es Ctrl+Mayús+-."),
("inicio","edicion",
 ["Ctrl+Z deshace la última acción.",
  "Ctrl+E selecciona todo el documento.",
  "F8 activa el modo de extender selección.",
  "Ctrl+Retroceso borra la palabra completa a la DERECHA del cursor."],
 "D","Ctrl+Retroceso borra la palabra hacia la IZQUIERDA del cursor, no a la derecha."),
("inicio","edicion",
 ["Ctrl+B abre el panel de Navegación.",
  "Alt+Q lleva el foco al cuadro Buscar de la barra de título.",
  "Ctrl+I abre el cuadro de diálogo Ir a.",
  "El panel de Navegación (Ctrl+B) solo permite buscar texto; no lista los títulos del documento."],
 "D","El panel de Navegación tiene pestañas Títulos / Páginas / Resultados; la de Títulos lista la estructura de encabezados del documento."),
("inicio","estilos",
 ["«Actualizar automáticamente» en un estilo aplica los cambios de un párrafo a todo el texto con ese estilo.",
  "Un estilo de párrafo puede incluir a la vez formato de fuente y de párrafo.",
  "Un estilo de carácter se puede quitar sin borrar el texto, aplicando «Predeterminado».",
  "Los estilos solo se pueden aplicar desde el panel Estilos; no hay galería en la cinta."],
 "D","La pestaña Inicio tiene una galería de «Estilos rápidos» visible directamente en la cinta, sin necesidad de abrir el panel."),
("inicio","estilos",
 ["Ctrl+Mayús+W abre el panel Aplicar estilos.",
  "Ctrl+Mayús+1 aplica el estilo Título 1.",
  "Alt+Ctrl+2 aplica el estilo Título 2.",
  "Ctrl+Mayús+2 aplica el estilo Título 2."],
 "D","Prueba en vivo: Ctrl+Mayús+2 no hace nada en esta instalación; Título 2 se aplica con Alt+Ctrl+2."),
("inicio","portapapeles",
 ["Ctrl+Ins copia (método antiguo del portapapeles).",
  "Mayús+Ins pega.",
  "Mayús+Supr corta.",
  "Alt+Ctrl+V nunca pega el formato; solo divide la ventana."],
 "D","Prueba en vivo: Alt+Ctrl+V es el atajo de Pegar formato (pincel), no divide ninguna ventana."),
("inicio","portapapeles",
 ["F2 mueve el texto seleccionado al punto donde se pulse Entrar después.",
  "Ctrl+F3 acumula recortes sucesivos en el Spike.",
  "Ctrl+Mayús+F3 pega todo el contenido del Spike.",
  "Mayús+F2 («Copiar a») mueve el texto y lo borra del origen."],
 "D","Mayús+F2 es «Copiar a»: copia el texto a otro punto SIN borrarlo del origen y sin tocar el portapapeles normal."),
("inicio","parrafo-listas",
 ["Word permite crear listas numeradas, con viñetas y multinivel desde el grupo Párrafo.",
  "Se puede cambiar el símbolo de una viñeta por una imagen o un carácter personalizado.",
  "Una lista multinivel solo admite 3 niveles como máximo.",
  "Se puede reiniciar la numeración de una lista desde el menú contextual."],
 "C","Una lista multinivel admite hasta 9 niveles de sangría/numeración, no solo 3."),
("inicio","parrafo-espaciado",
 ["Ctrl+1 aplica interlineado sencillo.",
  "Ctrl+5 (fila superior) aplica interlineado 1,5.",
  "Ctrl+2 aplica interlineado doble.",
  "El interlineado «Exacto» ajusta el espacio automáticamente según el tamaño de fuente más grande de la línea."],
 "D","«Exacto» fija un valor de espacio constante sin importar el tamaño de fuente; el que se ajusta solo es «Mínimo»."),
("inicio","parrafo-tabulaciones",
 ["El diálogo Tabulaciones se abre con Alt,F,T.",
  "Se pueden fijar tabulaciones izquierda, derecha, centrada, decimal y de barra.",
  "Ctrl+Tab inserta una tabulación real dentro de una celda de tabla.",
  "Las tabulaciones solo se pueden colocar haciendo doble clic en la regla; nunca desde un cuadro de diálogo."],
 "D","Las tabulaciones se pueden fijar tanto desde la regla como desde el cuadro de diálogo Tabulaciones (Alt,F,T)."),
("inicio","parrafo-bordes",
 ["El botón Bordes permite aplicar un borde solo a un lado del párrafo.",
  "Se puede añadir sombreado de color de fondo a un párrafo desde el mismo grupo.",
  "Los bordes de párrafo solo admiten líneas de un único grosor fijo, sin poder cambiarlo.",
  "«Bordes y sombreado» permite elegir el estilo, color y ancho de la línea."],
 "C","El cuadro «Bordes y sombreado» deja elegir el ancho de línea entre varios valores; no está fijado a uno solo."),
("inicio","parrafo-sangria",
 ["Ctrl+H aplica sangría.",
  "Ctrl+F aplica sangría francesa.",
  "Ctrl+Mayús+H reduce la sangría francesa.",
  "Ctrl+Mayús+R quita toda la sangría del párrafo."],
 "D","Prueba en vivo: Ctrl+Mayús+R no quita la sangría en esta instalación; para eso se usa Ctrl+W."),
# ---------- INSERTAR (+14) ----------
("insertar","ilustraciones",
 ["Se pueden insertar imágenes desde «Imágenes de este dispositivo» y desde «Imágenes en línea».",
  "SmartArt permite crear diagramas y organigramas con texto estructurado.",
  "Una vez insertada una forma, no se puede cambiar su relleno ni su contorno.",
  "Los gráficos (Insertar ▸ Gráfico) abren una hoja de datos de Excel vinculada."],
 "C","Una forma admite cambiar relleno, contorno y efectos en cualquier momento desde Formato de forma."),
("insertar","ilustraciones",
 ["Se puede insertar una captura de pantalla completa o solo un recorte con «Recorte de pantalla».",
  "Un icono (Insertar ▸ Iconos) es una imagen vectorial editable en color y forma.",
  "Las imágenes insertadas siempre se ajustan «En línea con el texto» y no se puede cambiar.",
  "SmartArt tiene categorías como Lista, Proceso, Ciclo, Jerarquía y Relación."],
 "C","El ajuste de texto de una imagen se puede cambiar (cuadrado, estrecho, detrás del texto…) desde Formato de imagen."),
("insertar","ilustraciones",
 ["Una forma nueva se puede combinar con otras mediante herramientas de «Combinar formas».",
  "El grupo de Formato de forma aparece solo cuando hay una forma seleccionada (cinta contextual).",
  "Los modelos 3D solo se pueden ver; no se pueden rotar ni cambiar de perspectiva.",
  "Un gráfico admite cambiar su tipo (barras, líneas, circular…) después de insertarlo."],
 "C","Los modelos 3D insertados se pueden rotar libremente arrastrando el control central que muestran al seleccionarlos."),
("insertar","texto",
 ["Un cuadro de texto se puede vincular a otro para que el texto fluya de uno a otro.",
  "WordArt aplica efectos de texto decorativos predefinidos.",
  "Insertar ▸ Objeto solo permite insertar hojas de Excel; ningún otro tipo de archivo.",
  "Se puede insertar la fecha y hora con la opción de «Actualizar automáticamente»."],
 "C","Insertar ▸ Objeto admite muchos tipos de objeto incrustado (PDF, presentaciones, otros documentos…), no solo Excel."),
("insertar","texto",
 ["Una letra capital (Insertar ▸ Letra capital) puede colocarse «En texto» o «En margen».",
  "La línea de firma crea un cuadro para firma digital.",
  "Insertar ▸ Número de página inserta un campo dinámico que se actualiza solo.",
  "Los campos (Ctrl+F9) solo pueden usarse para mostrar la fecha; ningún otro dato."],
 "D","Word tiene decenas de tipos de campo (autor, título, número de página, referencia cruzada…), no solo la fecha."),
("insertar","encabezado-pie",
 ["Se puede tener un encabezado distinto en la primera página.",
  "«Vincular al anterior» permite que una sección use el mismo encabezado que la anterior.",
  "Los encabezados y pies de página no pueden contener imágenes; solo texto.",
  "Se puede configurar un encabezado diferente para páginas pares e impares."],
 "C","Un encabezado o pie de página admite imágenes (por ejemplo un logo) igual que cualquier otra zona del documento."),
("insertar","encabezado-pie",
 ["El número de página se puede insertar en el encabezado, el pie o los márgenes.",
  "Se puede reiniciar la numeración de página en un valor concreto.",
  "Al insertar un número de página, siempre se numeran las páginas desde el número 1 sin poder cambiarlo.",
  "Para editar el encabezado se puede hacer doble clic sobre la zona superior de la página."],
 "C","«Formato del número de página» permite iniciar la numeración en cualquier valor, no solo en 1."),
("insertar","simbolos",
 ["Insertar ▸ Símbolo abre una galería con los símbolos usados recientemente arriba.",
  "«Más símbolos» abre el cuadro de diálogo completo con distintas fuentes y subconjuntos.",
  "Los símbolos insertados no se pueden buscar por su código de carácter Unicode.",
  "Insertar ▸ Ecuación abre una cinta contextual propia para escribir fórmulas matemáticas."],
 "C","El cuadro de diálogo Símbolo tiene un campo «Código de carácter» para localizar un símbolo por su código Unicode."),
("insertar","simbolos",
 ["Word trae ecuaciones predefinidas listas para insertar (por ejemplo el área de un círculo).",
  "Se puede convertir una ecuación a su forma manuscrita para editarla a mano.",
  "Una vez insertado un símbolo, no se le puede asignar un atajo de teclado propio para repetirlo.",
  "El cuadro de diálogo Símbolo recuerda los últimos símbolos usados en la fila superior."],
 "C","El propio cuadro de diálogo Símbolo tiene un botón «Teclas» para asignarle una combinación propia a un símbolo."),
("insertar","vinculos",
 ["Insertar ▸ Hipervínculo permite enlazar a un archivo, una página web o un punto del mismo documento.",
  "Un hipervínculo se puede quitar sin borrar el texto, con «Quitar hipervínculo».",
  "Un marcador sirve para nombrar un punto del documento y poder enlazarlo después.",
  "Los hipervínculos en Word solo pueden apuntar a páginas web; nunca a otro documento."],
 "D","Un hipervínculo puede apuntar a un archivo local, a otro documento, a un correo electrónico o a un punto del mismo documento, no solo a páginas web."),
("insertar","formato-forma",
 ["El relleno de una forma puede ser un color sólido, un degradado, una textura o una imagen.",
  "El contorno de una forma se puede cambiar de grosor, color y estilo de línea.",
  "Los efectos de forma incluyen sombra, reflexión, iluminado y bisel.",
  "Una forma no puede tener texto dentro; para eso hace falta un cuadro de texto aparte."],
 "D","Se puede escribir texto directamente dentro de una forma con «Modificar texto» (clic derecho o F2)."),
("insertar","tablas",
 ["Una tabla se puede insertar arrastrando en la cuadrícula o especificando filas y columnas en un diálogo.",
  "Se puede convertir texto separado por tabulaciones en una tabla.",
  "Una tabla de Word no admite fórmulas ni cálculos; solo Excel puede hacerlo.",
  "Se puede dibujar una tabla a mano con «Insertar ▸ Tabla ▸ Dibujar tabla»."],
 "C","Herramientas de tabla ▸ Diseño (Presentación) ▸ Fórmula permite sumas y otras fórmulas básicas dentro de una tabla de Word."),
("insertar","paginas",
 ["Insertar ▸ Portada añade una galería de diseños de portada prediseñados.",
  "Insertar ▸ Página en blanco añade una página vacía en el punto del cursor.",
  "Insertar ▸ Salto de página fuerza al contenido siguiente a empezar en una página nueva.",
  "Una portada insertada desde la galería no se puede editar ni personalizar su texto."],
 "D","Los campos de una portada prediseñada (título, autor, fecha…) son editables como cualquier texto del documento."),
("insertar","multimedia",
 ["Insertar ▸ Vídeo en línea permite incrustar un vídeo desde una URL.",
  "Un clip de audio se puede insertar en el documento igual que una imagen.",
  "Los vídeos insertados no se pueden redimensionar; mantienen siempre su tamaño original.",
  "Al insertar un vídeo en línea aparece un control de reproducción sobre el propio documento."],
 "C","Un vídeo insertado se redimensiona igual que una imagen, arrastrando sus tiradores o desde Formato."),
]

by_sec = {}
for row in Q:
    by_sec.setdefault(row[0], []).append(row)

LETTERS = ["A", "B", "C", "D"]

total = 0
for sec, rows in by_sec.items():
    f = f"data/questions/{sec}.json"
    d = json.load(open(f, encoding="utf-8"))
    n0 = max(int(q["id"].split("-")[-1]) for q in d)
    for k, (_, topic, opts, correct, expl) in enumerate(rows, 1):
        tname = NAME[sec][topic]
        d.append({
            "id": f"{sec}-{n0+k}", "sourceFile": f"{sec}.json", "bloque": f"{sec.capitalize()} — {tname}",
            "tipo": "opcion_unica", "categoria": "concepto", "negativa": True,
            "section": sec, "topic": topic, "subtopic": None, "tema": tname,
            "sourceQuestionId": f"neg2-{sec}-{k:02d}", "generado": True,
            "enunciado": "Señale la afirmación INCORRECTA:",
            "opciones": [{"letter": L, "text": t} for L, t in zip(LETTERS, opts)],
            "matching": None, "respuesta": correct, "explicacion": expl,
        })
    d.sort(key=lambda q: (TO[sec].get(q["topic"], 99), str(q.get("topic") or ""), int(q["id"].split("-")[-1])))
    json.dump(d, open(f, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    open(f, "a", encoding="utf-8").write("\n")
    neg = sum(1 for q in d if q.get("negativa"))
    total += len(rows)
    print(f"{f}: +{len(rows)}  ->  negativa {neg}/{len(d)} ({round(100*neg/len(d),1)}%)")
print("TOTAL nuevas:", total)
