# -*- coding: utf-8 -*-
import json

tax = json.load(open("data/taxonomy.json", encoding="utf-8"))
NAME = {s["id"]: {t["id"]: t["name"] for t in s["topics"]} for s in tax["sections"]}
TO = {s["id"]: {t["id"]: i for i, t in enumerate(s["topics"])} for s in tax["sections"]}

# cada entrada: (section, topic, categoria, enunciado, [opciones 4], letra_correcta(=la FALSA), explicacion)
Q = [
# ============ INSERTAR (12) ============
("insertar","paginas","ruta","¿Cuál de estos comandos NO está en el grupo Páginas de Insertar?",
 ["Portada","Página en blanco","Salto de página","Salto de sección"],"D",
 "El grupo Páginas de Insertar tiene solo tres comandos: Portada, Página en blanco y Salto de página. «Salto de sección» está en Disposición ▸ Configurar página ▸ Saltos."),
("insertar","tablas","concepto","¿Cuál de estas opciones de autoajuste NO existe en el cuadro Insertar tabla?",
 ["Ancho de columna fijo","Autoajustar al contenido","Autoajustar a la ventana","Autoajustar al papel"],"D",
 "Las tres opciones reales de Autoajuste son Ancho de columna fijo, Autoajustar al contenido y Autoajustar a la ventana. «Autoajustar al papel» no existe."),
("insertar","ilustraciones","ruta","¿Cuál de estas subcategorías del desplegable Formas NO existe?",
 ["Líneas","Rectángulos","Formas básicas","Círculos y óvalos"],"D",
 "Las subcategorías reales son Líneas, Rectángulos, Formas básicas, Flechas de bloque, Formas de ecuación, Diagrama de flujo, Cintas y estrellas y Llamadas. No hay una subcategoría «Círculos y óvalos» (el óvalo está dentro de Formas básicas)."),
("insertar","ilustraciones","ruta","¿Cuál de estos comandos NO pertenece al grupo Ilustraciones de Insertar?",
 ["Imágenes","Formas","Iconos","Tabla"],"D",
 "Tabla tiene su propio grupo («Tablas»), justo antes de Ilustraciones. Imágenes, Formas e Iconos sí están en el grupo Ilustraciones."),
("insertar","formato-forma","ruta","¿Cuál de estos grupos NO pertenece a la cinta contextual Formato de forma?",
 ["Insertar formas","Estilos de forma","Accesibilidad","Ajustar página"],"D",
 "Formato de forma tiene siete grupos: Insertar formas, Estilos de forma, Estilos de WordArt, Texto, Accesibilidad, Organizar y Tamaño. No existe un grupo «Ajustar página» en esa cinta."),
("insertar","vinculos","ruta","¿Cuál de estos comandos NO pertenece al grupo Vínculos de Insertar?",
 ["Vínculo","Marcador","Referencia cruzada","Hipervínculo interno"],"D",
 "El grupo Vínculos tiene exactamente tres comandos: Vínculo, Marcador y Referencia cruzada. No existe un comando separado llamado «Hipervínculo interno»."),
("insertar","comentarios","atajo","¿Cuál de estas afirmaciones sobre comentarios es INCORRECTA?",
 ["El atajo para insertar un comentario es Alt+Ctrl+A","Un comentario se puede resolver","Alt+Ctrl+C también inserta un comentario","Los comentarios se anclan a una selección de texto"],"C",
 "Alt+Ctrl+C copia el formato de la selección (el pincel); no tiene nada que ver con los comentarios. El comentario se inserta con Alt+Ctrl+A."),
("insertar","encabezado-pie","ruta","¿Cuál de estos comandos NO está en el grupo Encabezado y pie de página de Insertar?",
 ["Encabezado","Pie de página","Número de página","Fecha y hora"],"D",
 "El grupo Encabezado y pie de página de la pestaña Insertar tiene solo tres comandos: Encabezado, Pie de página y Número de página. Fecha y hora está en el grupo Texto."),
("insertar","texto","ruta","¿Cuál de estos comandos NO está en el grupo Texto de Insertar?",
 ["Cuadro de texto","WordArt","Letra capital","Símbolo"],"D",
 "Símbolo tiene su propio grupo («Símbolos»), al final de la pestaña Insertar. Cuadro de texto, WordArt y Letra capital sí están en el grupo Texto."),
("insertar","simbolos","concepto","¿Cuál de estas afirmaciones sobre el cuadro Símbolo es FALSA?",
 ["Tiene una ficha Símbolos y otra Caracteres especiales","Muestra una fila de símbolos usados recientemente","El botón Teclas... abre Personalizar teclado","Tiene una tercera ficha llamada Ecuaciones"],"D",
 "El cuadro Símbolo solo tiene dos fichas: Símbolos y Caracteres especiales. No existe una ficha «Ecuaciones» ahí (la ecuación es un comando aparte, en el mismo grupo Símbolos)."),
("insertar","multimedia","concepto","¿Cuál de estas plataformas de vídeo NO aparece en el cuadro Insertar vídeo en línea?",
 ["YouTube","Vimeo","TED","Dailymotion"],"D",
 "Las plataformas disponibles son YouTube, SlideShare, Vimeo y TED. Dailymotion no aparece en la lista."),
("insertar","esignature","concepto","¿Cuál de estas afirmaciones sobre eSignature es INCORRECTA?",
 ["El grupo tiene el comando «Campos de eSignature»","Exige que el documento esté guardado en .docx","Si el documento está en .doc, Word lo convierte automáticamente a .docx","Abre un panel «Crear una solicitud de firma»"],"C",
 "Word NO convierte el .doc automáticamente: muestra el mensaje «Save this document as a .docx file to use eSignature» y no deja continuar hasta que lo guardes tú en .docx."),
# ============ INICIO (12) ============
("inicio","fuente","ruta","¿Cuál de estos comandos NO está en el grupo Portapapeles de Inicio?",
 ["Pegar","Copiar","Cortar","Borrar todo el formato"],"D",
 "«Borrar todo el formato» está en el grupo Fuente, no en Portapapeles (que tiene Pegar, Copiar, Cortar, Copiar formato y su lanzador)."),
("inicio","fuente","atajo","¿Cuál de estos atajos NO corresponde al formato de fuente en esta instalación?",
 ["Ctrl+N (negrita)","Ctrl+K (cursiva)","Ctrl+S (subrayado)","Ctrl+U (subrayado)"],"D",
 "En el esquema clásico español, negrita/cursiva/subrayado son Ctrl+N/Ctrl+K/Ctrl+S. Ctrl+U no tiene esa función (es el esquema internacional en inglés)."),
("inicio","fuente","atajo","¿Cuál de estas afirmaciones sobre subíndice y superíndice es FALSA?",
 ["Subíndice es Ctrl+Mayús+-","Ctrl+_ hace lo mismo que Ctrl+Mayús+-","Superíndice es Ctrl+Mayús++","Superíndice no tiene atajo de teclado en esta instalación"],"C",
 "Superíndice NO tiene atajo en esta instalación (probado en vivo: ni Ctrl+Mayús+=, ni Ctrl+Mayús++, ni Ctrl+Alt++). Solo se activa desde el botón o la casilla del cuadro Fuente."),
("inicio","parrafo-alineacion","atajo","¿Cuál de estos atajos de alineación es INCORRECTO en esta instalación?",
 ["Ctrl+Q = izquierda","Ctrl+T = centrar","Ctrl+R = derecha","Ctrl+J = justificar"],"C",
 "Ctrl+R no hace absolutamente nada en esta instalación. Alinear a la derecha es Ctrl+D."),
("inicio","parrafo-sangria","atajo","¿Cuál de estas afirmaciones sobre sangría es FALSA?",
 ["Ctrl+H aumenta la sangría (esquema clásico español)","Ctrl+F aplica sangría francesa","Ctrl+Mayús+R quita toda la sangría en esta instalación","Ctrl+W quita el formato de párrafo, sangrías incluidas"],"C",
 "Ctrl+Mayús+R NO quita la sangría en esta instalación, aunque el volcado se la asigne. Para quitar sangrías se usa Ctrl+W (prueba en vivo del usuario)."),
("inicio","parrafo-espaciado","atajo","¿Cuál de estas afirmaciones sobre interlineado es INCORRECTA?",
 ["Ctrl+1 = interlineado sencillo","Ctrl+5 (fila superior) = interlineado 1,5","Ctrl+2 = interlineado doble","Ctrl+0 cambia el interlineado a triple"],"D",
 "Ctrl+0 no toca el interlineado: restaura el zoom al 100 %. Los atajos de interlineado son Ctrl+1/Ctrl+5/Ctrl+2 (sencillo/1,5/doble)."),
("inicio","parrafo-bordes","ruta","¿Cuál de estos comandos NO está en el grupo Párrafo de Inicio?",
 ["Bordes","Sombreado","Mostrar todo","Estilos rápidos"],"D",
 "«Estilos rápidos» (la galería de estilos) tiene su propio grupo, «Estilos», independiente del grupo Párrafo."),
("inicio","parrafo-listas","atajo","¿Cuál de estas afirmaciones sobre listas es FALSA?",
 ["Viñetas y Numeración están en el grupo Párrafo","Lista multinivel permite niveles jerárquicos (1, 1.1, 1.1.1...)","El atajo de Viñetas es Ctrl+Mayús+L sin ninguna ambigüedad","Ctrl+Mayús+L también está asignado a Versalitas en el volcado"],"C",
 "El volcado asigna Ctrl+Mayús+L tanto a Versalitas como a Lista con viñetas: es un conflicto interno sin dirimir, no una asignación limpia."),
("inicio","estilos","atajo","¿Cuál de estas afirmaciones sobre los atajos de título es FALSA?",
 ["Ctrl+Mayús+1 aplica Título 1","Alt+Ctrl+2 aplica Título 2","Ctrl+Mayús+2 también aplica Título 2","Ctrl+Mayús+3 aplica Título 3"],"C",
 "Ctrl+Mayús+2 no hace nada en esta instalación (probado en vivo). El atajo real de Título 2 es Alt+Ctrl+2."),
("inicio","edicion","ruta","¿Cuál de estos comandos NO está en el grupo Edición de Inicio?",
 ["Buscar","Reemplazar","Seleccionar","Ir a"],"D",
 "El grupo Edición tiene tres comandos: Buscar, Reemplazar y Seleccionar. «Ir a» no es un botón de ese grupo (es un atajo de teclado, Ctrl+I, sin botón propio en la cinta)."),
("inicio","voz","atajo","¿Cuál de estas afirmaciones sobre Dictar es FALSA?",
 ["Está en el grupo Voz de Inicio","Su atajo es Alt+[","Convierte la voz en texto","Su atajo es Ctrl+Mayús+V"],"D",
 "No existe ningún atajo Ctrl+Mayús+V para Dictar. El atajo real, confirmado en vivo, es Alt+[."),
("inicio","complementos","atajo","¿Cuál de estas afirmaciones sobre el Editor es FALSA?",
 ["Se abre con F7","También se abre con Windows+F7","Revisa ortografía, gramática y estilo","F7 abre el panel de Impresión"],"D",
 "F7 abre el panel Editor (ortografía y gramática), no el panel de Impresión. El de Impresión se abre con Ctrl+P."),
# ============ ARCHIVO (10) ============
("archivo","informacion","concepto","¿Cuál de estas NO es una opción del menú Proteger documento?",
 ["Cifrar con contraseña","Restringir edición","Marcar como final","Comprimir imágenes"],"D",
 "«Comprimir imágenes» está en Guardar como ▸ Herramientas, no en el menú Proteger documento (que tiene: solo lectura, cifrar, restringir edición, restringir acceso, firma digital y marcar como final)."),
("archivo","informacion","concepto","¿Cuál de estas NO es una opción de «Comprobar si hay problemas»?",
 ["Inspeccionar documento","Comprobar accesibilidad","Comprobar compatibilidad","Comprobar ortografía"],"D",
 "«Comprobar ortografía» no está en ese menú de Backstage: la revisión ortográfica se hace desde la pestaña Revisar, no desde Información."),
("archivo","informacion","concepto","¿Cuál de estos NO aparece en el panel Información?",
 ["Propiedades del documento","Fechas relacionadas","Personas relacionadas","Configurar página"],"D",
 "«Configurar página» está en Disposición y en el panel Imprimir, no en el panel Información."),
("archivo","guardar","concepto","¿Cuál de estas NO es una opción del menú Herramientas del cuadro Guardar como?",
 ["Opciones para guardar...","Opciones generales...","Comprimir imágenes...","Comprobar accesibilidad..."],"D",
 "El menú Herramientas de Guardar como tiene: Conectar a unidad de red, Opciones para guardar, Opciones generales, Opciones web y Comprimir imágenes. No incluye Comprobar accesibilidad."),
("archivo","informacion","concepto","¿Cuál de estas fichas NO tiene el cuadro Propiedades avanzadas?",
 ["General","Resumen","Estadísticas","Seguridad"],"D",
 "El cuadro Propiedades avanzadas tiene cinco fichas: General, Resumen, Estadísticas, Contenido y Personalizar. No existe una ficha «Seguridad»."),
("archivo","guardar","concepto","¿Cuál de estos NO es un formato disponible en Guardar como?",
 [".docx",".docm",".odt",".pages"],"D",
 "«.pages» es el formato de Apple Pages y no aparece en la lista de Word. Sí están .docx, .docm (con macros) y .odt (OpenDocument)."),
("archivo","imprimir","concepto","¿Cuál de estas afirmaciones sobre el panel Imprimir es FALSA?",
 ["«Intercaladas» imprime 1,2,3,1,2,3...","Se puede imprimir a doble cara manualmente","El máximo de páginas por hoja es 16","El máximo de páginas por hoja es 4"],"D",
 "El desplegable de páginas por hoja llega hasta 16 (1, 2, 4, 6, 8, 16), no se queda en 4."),
("archivo","compartir","concepto","¿Cuál de estas NO es una opción del panel Compartir?",
 ["Cargar el documento a OneDrive","Adjuntar una copia como Documento de Word","Adjuntar una copia como PDF","Enviar por fax"],"D",
 "El panel Compartir no ofrece envío por fax. Las opciones reales son subir a OneDrive o adjuntar una copia (Word o PDF)."),
("archivo","guardar","concepto","¿Cuál de estas afirmaciones sobre Guardar es FALSA?",
 ["Si el documento está en OneDrive, Backstage muestra «Guardar una copia»","Si está guardado en local, muestra «Guardar como»","Guardar sobrescribe el archivo actual","La primera vez que usas Guardar en un documento nuevo, lo borra sin preguntar"],"D",
 "Guardar nunca borra nada: la primera vez que se usa en un documento sin nombre se comporta como Guardar como y pide dónde guardarlo."),
("archivo","imprimir","concepto","¿Cuál de estas fichas NO tiene el cuadro Configurar página cuando se abre desde el panel Imprimir?",
 ["Márgenes","Papel","Disposición","Fuente"],"D",
 "El cuadro Configurar página tiene tres fichas: Márgenes, Papel y Disposición. No existe una ficha «Fuente» ahí (eso es un cuadro distinto)."),
# ============ VISTA (6) ============
("vista","vistas","atajo","¿Cuál de estos atajos de vista es INCORRECTO?",
 ["Alt+Ctrl+D = Diseño de impresión","Alt+Ctrl+Q = Vista Esquema","Alt+Ctrl+N = Vista Normal/Borrador","Alt+Ctrl+L = Modo de lectura"],"D",
 "No existe un atajo Alt+Ctrl+L para el Modo de lectura. Los cuatro atajos reales de vista son Alt+Ctrl+D/Q/N/I (Diseño de impresión/Esquema/Normal/vista preliminar)."),
("vista","ventana","atajo","¿Cuál de estas afirmaciones sobre Alt+Ctrl+V es FALSA?",
 ["En esta instalación pega el formato copiado","Es a Pegar formato lo que Alt+Ctrl+C es a Copiar formato","El volcado también lo asigna a «Dividir ventana»","En la práctica, divide la ventana del documento en dos paneles"],"D",
 "En vivo, Alt+Ctrl+V NO divide la ventana: pega el formato copiado con Alt+Ctrl+C. Dividir la ventana no tiene atajo; se hace desde Vista ▸ Ventana ▸ Dividir."),
("vista","ventana","ruta","¿Cuál de estos comandos NO está en el grupo Ventana de Vista?",
 ["Nueva ventana","Dividir","Ver en paralelo","Panel de navegación"],"D",
 "El Panel de navegación está en el grupo Mostrar, no en el grupo Ventana."),
("vista","zoom","concepto","¿Cuál de estas afirmaciones sobre el zoom es FALSA?",
 ["El rango va del 10 % al 500 %","Ctrl + rueda del ratón cambia el zoom de 10 en 10","Ctrl+- aleja el zoom","Ctrl++ también aleja el zoom"],"D",
 "Ctrl++ acerca el zoom, no lo aleja. El que aleja es Ctrl+- (de 10 en 10 puntos)."),
("vista","vistas","ruta","¿Cuál de estas vistas NO está entre los botones del grupo Vistas?",
 ["Modo de lectura","Diseño de impresión","Diseño Web","Vista previa de impresión"],"D",
 "La «Vista previa de impresión» no es un botón del grupo Vistas: se accede desde Archivo ▸ Imprimir. El grupo Vistas tiene Modo de lectura, Diseño de impresión, Diseño Web, Vista Esquema y Vista Borrador."),
("vista","macros","ruta","¿Cuál de estas afirmaciones sobre el grupo Macros de Vista es FALSA?",
 ["Contiene el comando Macros","Permite grabar una macro","Abre el editor de Visual Basic (VBE) con Alt+F11","Está en la pestaña Programador, no en Vista"],"D",
 "El grupo Macros está en la pestaña Vista (la pestaña Programador, si está activada, tiene su propio grupo de macros aparte)."),
# ============ DISPOSICIÓN (8) ============
("disposicion","configurar-pagina","ruta","¿Cuál de estos comandos NO está en el grupo Configurar página de Disposición?",
 ["Márgenes","Orientación","Tamaño","Estilos"],"D",
 "«Estilos» es un grupo de la pestaña Inicio. Configurar página tiene Márgenes, Orientación, Tamaño, Columnas, Saltos, Números de línea y Guiones."),
("disposicion","configurar-pagina","concepto","¿Cuál de estas afirmaciones sobre márgenes es FALSA?",
 ["«Normal» es 2,5/3 cm en esta instalación","«Estrecho» es 1,27 cm en los cuatro lados","«Ancho» aplica 5,08 cm en los cuatro lados","«Reflejado» usa Interior/Exterior en vez de Izquierdo/Derecho"],"C",
 "«Ancho» solo aplica 5,08 cm en los laterales; arriba y abajo mantiene 2,54 cm, no 5,08 en los cuatro lados."),
("disposicion","configurar-pagina","concepto","¿Cuál de estos tamaños de papel es INCORRECTO?",
 ["A4 = 21 × 29,7 cm","Carta = 21,59 × 27,94 cm","Oficio = 21,59 × 35,56 cm","A4 y Carta son idénticos"],"D",
 "A4 y Carta NO son idénticos: A4 mide 21×29,7 cm y Carta 21,59×27,94 cm."),
("disposicion","configurar-pagina","concepto","¿Cuál de estas afirmaciones sobre Columnas es FALSA?",
 ["El desplegable ofrece Una/Dos/Tres/Izquierda/Derecha","«Izquierda» crea dos columnas del mismo ancho","El cuadro Columnas tiene la casilla «Línea entre columnas»","Por defecto el cuadro Columnas propone 5 columnas al elegir «Más columnas...»"],"B",
 "«Izquierda» crea dos columnas de ancho DESIGUAL (la estrecha a la izquierda), no del mismo ancho."),
("disposicion","configurar-pagina","ruta","¿Cuál de estos NO es un salto de sección del menú Saltos?",
 ["Página siguiente","Continua","Página par","Columna"],"D",
 "«Columna» es un salto de página, no de sección. Los saltos de sección son Página siguiente, Continua, Página par y Página impar."),
("disposicion","parrafo-disposicion","ruta","¿Cuál de estas afirmaciones sobre el grupo Párrafo de Disposición es FALSA?",
 ["Incluye la sangría izquierda y derecha","Incluye el espaciado antes y después","Incluye los botones de alineación (izquierda/centro/derecha/justificar)","El espaciado por defecto es Antes 0 pto / Después 8 pto"],"C",
 "La alineación está en el grupo Párrafo de la pestaña Inicio, no en el de Disposición (que solo tiene sangría y espaciado)."),
("disposicion","organizar","ruta","¿Cuál de estos comandos NO está en el grupo Organizar de Disposición?",
 ["Posición","Ajustar texto","Alinear","Insertar formas"],"D",
 "«Insertar formas» es un grupo de la cinta contextual Formato de forma, no del grupo Organizar de Disposición."),
("disposicion","organizar","concepto","¿Cuál de estas afirmaciones sobre el menú Alinear es FALSA?",
 ["«Alinear verticalmente» centra los objetos en horizontal","«Alinear al medio» centra los objetos en vertical","Por defecto está marcada la opción «Alinear a la página»","Existen «Distribuir horizontalmente» y «Distribuir verticalmente»"],"C",
 "Por defecto está marcada «Alinear al margen», no «Alinear a la página»."),
# ============ DISEÑO (6) ============
("diseno","formato-documento","ruta","¿Cuál de estos comandos NO está en el grupo Formato del documento de Diseño?",
 ["Temas","Colores","Fuentes","Marca de agua"],"D",
 "«Marca de agua» está en el grupo Fondo de página, no en Formato del documento."),
("diseno","formato-documento","concepto","¿Cuál de estas afirmaciones sobre Temas es FALSA?",
 ["El tema «Office» usa Aptos Display/Aptos","Existe un tema llamado «Vintage»","«Guardar tema actual...» genera un archivo .thmx","«Restablecer tema de plantilla» vuelve al tema de la plantilla base"],"B",
 "No existe ningún tema llamado «Vintage» en la galería de Temas de esta versión de Word."),
("diseno","formato-documento","concepto","¿Cuál de estas opciones integradas de Espaciado entre párrafos NO existe?",
 ["Sin espacio entre párrafos","Compacto","Estrecho","Amplio"],"D",
 "Las seis opciones integradas son Sin espacio entre párrafos, Compacto, Estrecho, Abierto, Moderado y Doble. No existe una llamada «Amplio»."),
("diseno","fondo-pagina","ruta","¿Cuál de estos comandos NO está en el grupo Fondo de página de Diseño?",
 ["Marca de agua","Color de página","Bordes de página","Efectos"],"D",
 "«Efectos» está en el grupo Formato del documento, no en Fondo de página (que solo tiene Marca de agua, Color de página y Bordes de página)."),
("diseno","fondo-pagina","concepto","¿Cuál de estas afirmaciones sobre Bordes de página es FALSA?",
 ["Los valores son Ninguno/Cuadro/Sombra/3D/Personalizado","El ancho máximo de línea es 6 pto","«Aplicar a» solo permite «Todo el documento»","Existe un desplegable «Arte» con motivos gráficos"],"C",
 "«Aplicar a» también ofrece Esta sección, Esta sección: solo la primera página y Esta sección: todas excepto la primera."),
("diseno","formato-documento","concepto","¿Cuál de estas afirmaciones sobre el menú Colores es FALSA?",
 ["«Escala de grises» es una combinación de colores del tema","«Escala de grises» convierte también las fotos insertadas a blanco y negro","«Personalizar colores...» permite guardar una combinación con nombre","Existen combinaciones como Azul, Azul II y Verde azulado"],"B",
 "«Escala de grises» solo cambia la paleta de colores del tema; las imágenes insertadas mantienen su color original."),
# ============ REFERENCIAS (6) ============
("referencias","tabla-contenido","ruta","¿Cuál de estos NO es un grupo de la pestaña Referencias?",
 ["Tabla de contenido","Notas al pie","Citas y bibliografía","Tabla de contenidos multimedia"],"D",
 "No existe un grupo llamado «Tabla de contenidos multimedia». Los grupos reales son Tabla de contenido, Notas al pie, Citas y bibliografía, Títulos e Índice."),
("referencias","tabla-contenido","concepto","¿Cuál de estas afirmaciones sobre el cuadro Tabla de contenido es FALSA?",
 ["Comparte cuadro con Índice y Tabla de ilustraciones","Tiene 7 formatos, incluidos Sofisticado y Moderno","«Modificar...» edita los estilos Título 1 a Título 9","Por defecto muestra 3 niveles"],"C",
 "«Modificar...» edita los estilos TDC 1 a TDC 9 (las líneas de la propia tabla), no los estilos Título."),
("referencias","notas","atajo","¿Cuál de estos atajos es INCORRECTO?",
 ["Alt+Ctrl+O = nota al pie","Alt+Ctrl+L = nota al final","Alt+Ctrl+A = comentario","Alt+Ctrl+O = nota al final"],"D",
 "Alt+Ctrl+O inserta una nota AL PIE, no al final (eso es Alt+Ctrl+L). No puede ser las dos cosas a la vez."),
("referencias","citas-bibliografia","concepto","¿Cuál de estas afirmaciones sobre estilos de cita es FALSA?",
 ["El estilo por defecto es APA","Existe el estilo Vancouver","Existe el estilo MLA","Existe el estilo Chicago"],"B",
 "No existe el estilo «Vancouver» en el menú Estilo de Word. Sí están APA, Chicago, GB7714, GOST, Harvard-Anglia, IEEE, ISO 690, MLA, SIST02 y Turabian."),
("referencias","titulos","ruta","¿Cuál de estos NO es un rótulo de fábrica del cuadro Título?",
 ["Ilustración","Ecuación","Tabla","Figura"],"D",
 "En el Word en español el rótulo se llama «Ilustración», no «Figura». Los tres rótulos de fábrica son Ilustración, Ecuación y Tabla."),
("referencias","indice","concepto","¿Cuál de estas afirmaciones sobre el índice alfabético es FALSA?",
 ["Se genera de entradas marcadas con «Marcar entrada»","«Automarcar» usa un archivo de concordancia","Se genera a partir de los estilos de título, igual que la tabla de contenido","Por defecto usa 2 columnas"],"C",
 "El índice NO se genera de los estilos de título (eso es la tabla de contenido): se genera de entradas marcadas a mano o con Automarcar."),
# ============ REVISAR (5) ============
("revisar","revision-ortografica","atajo","¿Cuál de estas afirmaciones sobre el Editor de Revisar es FALSA?",
 ["Se abre con F7","También se abre con Windows+F7","Revisa ortografía, gramática y estilo","Se abre con Ctrl+F7"],"D",
 "Ctrl+F7 no está documentado con esa función. El Editor se abre con F7 (y, confirmado en vivo, también con Windows+F7)."),
("revisar","seguimiento","atajo","¿Cuál de estas afirmaciones sobre el control de cambios es FALSA?",
 ["Se activa o desactiva con Ctrl+Mayús+E","Está relacionado con el grupo Seguimiento","Ctrl+E también activa el control de cambios","Permite ver «Todas las revisiones» o «Simple markup»"],"C",
 "Ctrl+E selecciona todo el documento; no tiene nada que ver con el control de cambios. El atajo real es Ctrl+Mayús+E."),
("revisar","idioma","atajo","¿Cuál de estas afirmaciones sobre el Traductor es FALSA?",
 ["Se abre con Alt+Mayús+F7","No aparece en el volcado v2608","Está confirmado en vivo por el usuario","Su atajo es Ctrl+Mayús+T"],"D",
 "No existe un atajo Ctrl+Mayús+T para el Traductor. El atajo real, confirmado en vivo (no está en el volcado), es Alt+Mayús+F7."),
("revisar","voz","atajo","¿Cuál de estas afirmaciones sobre «Leer en voz alta» es FALSA?",
 ["Su atajo es Alt+Ctrl+Espacio","Está confirmado en vivo","Hace lo mismo que Dictar (Alt+[)","Convierte texto a voz, no voz a texto"],"C",
 "Son funciones opuestas: Dictar convierte VOZ en texto; Leer en voz alta convierte TEXTO en voz. No son lo mismo."),
("revisar","estructura","concepto","¿Cuál de estas afirmaciones sobre la pestaña Revisar es FALSA?",
 ["Tiene dos grupos llamados literalmente «Revisión»","Uno es el de corrección ortográfica y otro el de visualización del marcado","Los dos comparten el mismo ribbonGroup «Revisión»","Solo existe un grupo llamado «Revisión» en toda la pestaña"],"D",
 "Revisar tiene DOS grupos distintos que se llaman igual, «Revisión»: uno de corrección (Ortografía) y otro de visualización del marcado de cambios."),
# ============ CORRESPONDENCIA (1) ============
("correspondencia","campos-combinacion","ruta","¿Cuál de estos comandos NO está en el grupo Escribir e insertar campos de Correspondencia?",
 ["Bloque de direcciones","Línea de saludo","Reglas","Sobres"],"D",
 "«Sobres» está en el grupo Crear, al principio de la pestaña Correspondencia, no en Escribir e insertar campos."),
]

def build(section, topic, categoria, enun, opts, correct_letter, expl):
    letters = ["A","B","C","D"]
    opciones = [{"letter": l, "text": t} for l, t in zip(letters, opts)]
    return {
        "section": section, "topic": topic, "categoria": categoria,
        "enunciado": enun, "opciones": opciones, "respuesta": correct_letter,
        "explicacion": expl,
    }

by_sec = {}
for row in Q:
    r = build(*row)
    by_sec.setdefault(r["section"], []).append(r)

total = 0
for sec, rows in by_sec.items():
    f = f"data/questions/{sec}.json"
    d = json.load(open(f, encoding="utf-8"))
    n0 = max(int(q["id"].split("-")[-1]) for q in d)
    for k, r in enumerate(rows, 1):
        tname = NAME[sec][r["topic"]]
        d.append({
            "id": f"{sec}-{n0+k}", "sourceFile": f"{sec}.json", "bloque": f"{sec.capitalize()} — {tname} (negativa)",
            "tipo": "opcion_unica", "categoria": r["categoria"], "negativa": True,
            "section": sec, "topic": r["topic"], "subtopic": None, "tema": tname,
            "sourceQuestionId": f"neg-{sec}-{k:02d}", "generado": True,
            "enunciado": r["enunciado"], "opciones": r["opciones"], "matching": None,
            "respuesta": r["respuesta"], "explicacion": r["explicacion"],
        })
    d.sort(key=lambda q: (TO[sec].get(q["topic"], 99), int(q["id"].split("-")[-1])))
    json.dump(d, open(f, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    open(f, "a", encoding="utf-8").write("\n")
    total += len(rows)
    print(f"{f}: +{len(rows)} negativas")
print("TOTAL nuevas:", total)
